export const FONTS = {
  w300: 'Nunito-Light',
  w400: 'Nunito-Regular',
  w500: 'Nunito-Medium',
  w600: 'Nunito-SemiBold',
  w700: 'Nunito-Bold',
};

export const pregnancyComplications = [
  'None',
  'Neonate Issues',
  'Placental or uterine problems',
  'Gastational Diabetes',
  'High Blood Pressure',
  'Thyroid Issues',
  'Asthma',
  'Allergies',
  'Rh Incompatibility',
  'Other',
];

export const COLORS = {
  PRIMARY: 'rgba(94, 158, 163, 1)',
  SECONDARY: 'rgba(216, 119, 119, 1)',
  SHADOW: 'rgba(0, 0, 0, 0.15)',
  WHITE: 'rgba(255, 255, 255, 1)',
  BLACK: 'rgba(0, 0, 0, 0.75)',
  GREY: 'rgba(0, 0, 0, 0.5)',
  ONLINE: 'rgba(126, 214, 72, 1)',
  OFFLINE: 'rgba(255, 194, 116, 1)',
  RED: 'rgba(216, 119, 119, 1)',
  TEXTBOX: 'rgba(245, 245, 245, 1)',
  PAYMENTBACKGROUND: 'rgba(126, 177, 181, 0.4)',
  SENDER_CHAT_BUBBLE: 'rgba(126, 177, 181, 0.29)',
  RECEIVER_CHAT_BUBBLE: 'rgba(126, 177, 181, 1)',
  UNREAD_BUBBLE: 'rgba(228, 136, 136, 1)',
};

export const IMAGES = {
  CHECKED_SQUARE: require('../assets/images/checked_square.png'),
  UNCHECKED_SQUARE: require('../assets/images/unchecked_square.png'),
  BELL: require('../assets/images/notifications.png'),
  LOGO: require('../assets/images/logo.png'),
  SEARCH: require('../assets/images/search.png'),
  UNCHEKED_CIRCLE: require('../assets/images/unchecked_circle.png'),
  UNCHEKED_SQUARE: require('../assets/images/unchecked_square.png'),
  TICK: require('../assets/images/tick.png'),
  DROPDOWN1: require('../assets/images/dropdown1x.png'),
  DROPDOWN: require('../assets/images/dropdown.png'),
  DRAWER: require('../assets/images/drawer.png'),
  CROSS: require('../assets/images/cross.png'),
  CHEKED_CIRCLE: require('../assets/images/checked_circle.png'),
  CHEKED_SQUARE: require('../assets/images/checked_square.png'),
  CALENDAR: require('../assets/images/calendar.png'),
  BACKGROUND: require('../assets/images/butterflyback.png'),
  APPLE: require('../assets/images/apple.png'),
  FACEBOOK: require('../assets/images/facebook.png'),
  GOOGLE: require('../assets/images/google.png'),
  CLOCK: require('../assets/images/clock.png'),
  BACK_ARROW: require('../assets/images/back_arrow.png'),
  IMAGE_PICKER: require('../assets/images/image_picker3x.png'),
  HOMEICONUNFOCUSED: require('../assets/images/home-unfocused.png'),
  HOMEICONFOCUSED: require('../assets/images/home-focused.png'),
  CHATICONFOCUSED: require('../assets/images/chat-focused.png'),
  CHATICONUNFOCUSED: require('../assets/images/chat-unfocused.png'),
  LEARNICONFOCUSED: require('../assets/images/learn-focused.png'),
  LEARNICONUNFOCUSED: require('../assets/images/learn-unfocused.png'),
  CARETEAMICONFOCUSED: require('../assets/images/careteam-focused.png'),
  CARETEAMICONUNFOCUSED: require('../assets/images/careteam-unfocused.png'),
  MEETICONFOCUSED: require('../assets/images/meet-focused.png'),
  MEETICONUNFOCUSED: require('../assets/images/meet-unfocused.png'),
  DRAWERICON_HOME: require('../assets/images/drawer-home.png'),
  DRAWERICON_INVITATIONS: require('../assets/images/drawer-invitations.png'),
  DRAWERICON_VISIT: require('../assets/images/drawer-homevisit.png'),
  DRAWERICON_TNC: require('../assets/images/drawer-tnc.png'),
  DRAWERICON_HOWITWORKS: require('../assets/images/drawer-howitworks.png'),
  DRAWERICON_ABOUTUS: require('../assets/images/drawer-aboutus.png'),
  DRAWERICON_FAQ: require('../assets/images/drawer-faq.png'),
  DRAWERICON_LOGOUT: require('../assets/images/drawer-logout.png'),
  TICK_CIRCLE: require('../assets/images/tick-circle.png'),
  CROSS_CIRCLE: require('../assets/images/cross-circle.png'),
  DELETE_USER: require('../assets/images/delete-user.png'),
  CHAT_SEND: require('../assets/images/chat-send-icon.png'),
  INCOMING: require('../assets/images/incoming.png'),
  ENDCALL: require('../assets/images/endcall.png'),
};
